# Generated by Django 4.1.4 on 2022-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="media/profile_pics/default.png", upload_to="profile_pics/"
            ),
        ),
    ]
