# Generated by Django 4.1.4 on 2023-01-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
