# Generated by Django 4.1.4 on 2022-12-17 23:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="../static/img/smokeymtn.jpg", upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tagline",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
