# Generated by Django 4.1.4 on 2022-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="../static/img/smokeymtn.jpg", upload_to="articles/"
            ),
        ),
    ]
