# Generated by Django 4.1.4 on 2022-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(default=True, verbose_name="allow comments"),
        ),
    ]
